---
- name: "PLAY 1: Backup of running config"
  hosts: cisco_routers
  connection: network_cli
  tasks:
    - name: "TASK 1: Get running config + store in show_run_output variable"
      ios_command:
        commands: "show running-config"
      register: show_run_output

    - name: "TASK 2: Copy the content of variable to show_run directory"
      copy:
        content: "{{ show_run_output.stdout[0] }}\n"
        dest: "/etc/ansible/outputs/show_run/{{ inventory_hostname }}_show_run.txt"
