---
- hosts: csr1k
  gather_facts: true
  connection: local

  tasks:
   - name: show run
   ios_commands:
     - show run
     hosts: "{{ ansible_host }}"
     username: cisco
     password: cisco
     register: config

  - name: save outpout to /etc/ansible/backups/backup_cisco_router_01
  copy:
  content: "{{ config.stdout[0] }}"
  dest: "/etc/ansible/backups/backup_cisco_router_01/show_run_{{ inventory_hostname }}.txt"
